# Generated by Django 4.1.3 on 2022-11-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='imageProfile',
        ),
    ]
