# Generated by Django 4.1.3 on 2022-11-24 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_profile_pic'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savepost',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
