# Generated by Django 4.1.3 on 2022-11-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_imagepost_postid_alter_post_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='image',
            new_name='post_image',
        ),
    ]
