# Generated by Django 4.1.3 on 2022-11-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_image_imagepost_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='post_image',
            new_name='image',
        ),
    ]
